config/routes.rb
Rails.application.routes.draw do

  root 'characters#new'

  resources :characters do
    resources :notes
  end

  get "search", to: "searcher#show"
  get "search/characters", to: "searcher#characters"
  get "search/notes", to: "searcher#notes"

end

app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id         :integer          not null, primary key
#  name       :string
#  location   :string
#  alignment  :string
#  role       :string
#  occupation :string
#  allegiance :string
#  goals      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Character < ActiveRecord::Base
  has_many :notes, as: :notable

  validates :name, presence: true
  validates :location, presence: true
  validates :occupation, presence: true
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id           :integer          not null, primary key
#  content      :string
#  notable_id   :integer
#  notable_type :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Note < ActiveRecord::Base
  belongs_to :notable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def new
  end

  def create
    puts permitted_params
    character = Character.create(permitted_params)
    render json: character
  end

  def show
    @character = Character.find(params[:id])
  end

  def index
    @characters = Character.all

    render json: @characters
  end

  def edit
    @character = Character.find(params[:id])
  end

  private
    def permitted_params
      params.require(:character).permit(:name, :location, :alignment, :role, :occupation, :allegiance, :goals)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def show
  end

  def edit

  end

  def new
  end

  def create
    character = Character.find(params[:character_id])
    character.notes.create(permitted_params)
    redirect_to character_path(character)
  end

  def index
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy
    redirect_to character_path(params[:character_id])
  end

  private
    def permitted_params
      params.permit(:content)
    end
end

app/controllers/searcher_controller.rb
class SearcherController < ApplicationController
  def show
    # Displays the searcher default page
  end

  def characters
    unless params[:search].empty?
      # Searches through the characters table for all the things that match X
      names = Character.where("name = ?", params[:search])#.pluck("id")
      locations = Character.where("location = ?", params[:search])#.pluck("id")
      alignments = Character.where("alignment = ?", params[:search])#.pluck("id")
      roles = Character.where("alignment = ?", params[:search])#.pluck("id")
      occupations = Character.where("role = ?", params[:search])#.pluck("id")
      allegiances = Character.where("allegiance = ?", params[:search])#.pluck("id")
      goals = Character.where("goals = ?", params[:search])#.pluck("id")

      characters = [names, locations, alignments, roles, occupations, allegiances, goals]
      @characters = []

      character_ids = []

      # Search through each of the returned arrays, and only add the character to the @characters if it hasn't already been added.
      # Note: this can likely be done with a join, but sleep deprivation says no!
      characters.length.times do |i|
        characters[i].each do |c|
          if !character_ids.include?(c.id)
            character_ids = c.id
            @characters.push(c)
          end
        end
      end

      @characters
    else
      @characters = []
    end
  end

  def notes
    # Should do what characters does.
    # This means it needs to look in the individual strings I guess. This'll be slow...
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/searcher_helper.rb
module SearcherHelper
end

app/views/characters/edit.html.haml
<h1>Characters#edit</h1>
<p>Find me in app/views/characters/edit.html.erb</p>

app/views/characters/index.html.haml
%table.characters__table
  %thead.characters__table-header
    %tr.characters__table-header-row
      %th Name
      %th Location
      %th Alignment
      %th Role
      %th Occupation
      %th Allegiance
      %th Goals
  %tbody.characters__table-body
    -@characters.each do |character|
      %tr.characters__row{data: {character_id: character.id}}
        %td
          = character.name
        %td
          = character.location
        %td
          = character.alignment
        %td
          = character.role
        %td
          = character.occupation
        %td
          = character.allegiance
        %td
          = character.goals

app/views/characters/new.html.haml
= form_tag '/characters' do
  = field_set_tag do
    = label_tag :name, 'Name:'
    = text_field_tag :name
    = label_tag :location, "Location"
    = text_field_tag :location
    = label_tag :alignment, "Alignment"
    = text_field_tag :alignment
    = label_tag :role, "Role"
    = text_field_tag :role
    = label_tag :occupation, "Occupation"
    = text_field_tag :occupation
    = label_tag :allegiance, "Allegiance"
    = text_field_tag :allegiance
    = label_tag :goals, "Goals"
    = text_field_tag :goals
    = submit_tag 'Save Changes'

app/views/characters/show.html.haml
%div.character
  %div.character__name
    Name:
    = @character.name
  %div.character__location
    Location:
    = @character.location
  %div.character__alignment
    Alignment:
    = @character.alignment
  %div.character__role
    Role:
    = @character.role
  %div.character__occupation
    Occupation:
    = @character.occupation
  %div.character__allegiance
    Allegiance:
    = @character.allegiance
  %div.character__goals
    Goals:
    = @character.goals
  %div.character__notes
    = link_to "Add Note", new_character_note_path(@character)
    %table.character__notes__table
      %thead.character__notes__table-header
        %tr.character__notes__table-header-row
          %th Note
          %th Created On
          %th Last Updated
          %th
          %th
      %tbody.character__notes__table-body
        -@character.notes.each do |note|
          %tr.character__notes__table-row
            %td
              = note.content
            %td
              = note.created_at .to_date
            %td
              = note.updated_at.to_date
            %td
              = link_to "Edit Note", edit_character_note_path(@character, note)
            %td
              = link_to "Delete", character_note_path(@character, note), method: 'delete'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dnd</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
</body>
</html>

app/views/notes/edit.html.haml
%h1 Notes#edit
%p Find me in app/views/notes/edit.html.haml

app/views/notes/index.html.haml
%h1 Notes#index
%p Find me in app/views/notes/index.html.haml

app/views/notes/new.html.haml
= form_tag character_notes_path do
  = field_set_tag do
    = label_tag :content, 'Note:'
    = text_field_tag :content
    = submit_tag 'Create Note'

app/views/notes/show.html.haml
%h1 Notes#show
%p Find me in app/views/notes/show.html.haml

app/views/searcher/characters.html.haml
%table.characters__table
  %thead.characters__table-header
    %tr.characters__table-header-row
      %th Name
      %th Location
      %th Alignment
      %th Role
      %th Occupation
      %th Allegiance
      %th Goals
  %tbody
    -@characters.each do |character|
      %tr.characters__row{data: {character_id: character.id}}
        %td
          = character.name
        %td
          = character.location
        %td
          = character.alignment
        %td
          = character.role
        %td
          = character.occupation
        %td
          = character.allegiance
        %td
          = character.goals

app/views/searcher/show.html.haml
= form_tag search_characters_path, method: 'get' do
  = field_set_tag do
    = label_tag :search, 'Search Characters:'
    = text_field_tag :search

= form_tag search_notes_path, method: 'get' do
  = field_set_tag do
    = label_tag :search, 'Search Notes:'
    = text_field_tag :search